baseURL = "/"
languageCode = "en-us"
title = "JAMstack Themes"
theme = "jamstackthemes"
paginate = 18
summaryLength = 10
# enableGitInfo = false
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[params]
  google_analytics_id = ""
  description = "A list of Themes and Starters for JAMstack Sites."
  stackbit_button = true
  [theme_card]
    show_archetype_icons = false
    show_services_icons = false

[taxonomies]
  ssg = "ssg"
  cms = "cms"
  css = "css"
  archetype = "archetype"
  services = "services"

[outputs]
  home = ["HTML","RSS","JSON"]
  section = ["HTML","RSS"]

[frontmatter]
  lastmod = [":git", "lastmod", ":fileModTime", ":default"]

# Main Menu
[[menu.main]]
	name = "New Themes"
	url = "/"
    weight = 1

[[menu.main]]
	name = "All Themes"
	url = "/themes/"
    weight = 2
