[build]
  publish = "public"
  command = "npm run deploy"

[build.environment]
  HUGO_VERSION = "0.71.1"

[context.deploy-preview]
  command = "npm run deploy"

[[headers]]
  for = "/index.json"
  [headers.values]
  Access-Control-Allow-Origin = "*"